spring.application.name=api-gateway

# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Key + Value serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Idempotent producer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647
spring.kafka.producer.enable-idempotence=true
spring.kafka.producer.max-in-flight-requests-per-connection=5

#Reliability tuning
spring.kafka.producer.delivery-timeout-ms=120000
spring.kafka.producer.request-timeout-ms=30000

# Batching (performance)
spring.kafka.producer.batch-size=16384
spring.kafka.producer.linger-ms=5
spring.kafka.producer.buffer-memory=33554432

logging.level.org.springframework.kafka=DEBUG

base.baseUrl=http://localhost:8081
